# Generated by Django 4.2.1 on 2024-02-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='company_dicription',
            new_name='company_description',
        ),
    ]
