# Generated by Django 4.2.1 on 2024-02-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_company_dicription_employer_company_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_description',
            field=models.TextField(),
        ),
    ]
