# Generated by Django 4.2.1 on 2024-02-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
