# Generated by Django 5.0.1 on 2024-01-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_app', '0002_employer_groups_employer_is_active_employer_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='login',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
