# Generated by Django 5.0.1 on 2024-01-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_app', '0003_alter_employer_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='description',
        ),
    ]
