# Generated by Django 5.0.1 on 2024-01-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_app', '0004_remove_employer_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='employer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
