# Generated by Django 4.2.1 on 2024-02-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_app', '0006_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='employer_ID',
            new_name='employer',
        ),
    ]
