# Generated by Django 4.2.1 on 2024-02-15 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_app', '0008_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
