# Generated by Django 4.2.1 on 2024-02-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop_app', '0009_delete_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
