# Generated by Django 4.2.1 on 2024-02-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='company',
            new_name='employer',
        ),
    ]
