# Generated by Django 4.2.1 on 2024-03-17 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='price',
        ),
    ]
