# Generated by Django 4.2.1 on 2024-02-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_description_remove_service_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='employer',
        ),
    ]
