# Generated by Django 4.2.1 on 2024-02-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_subservice_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='service_name',
        ),
        migrations.RenameField(
            model_name='subservice',
            old_name='name',
            new_name='sub_service_name',
        ),
    ]
