# Generated by Django 4.2.1 on 2024-03-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
        ('services', '0004_category_employerservice_remove_subservice_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Subservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='employerservice',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='employerservice',
            name='service',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='EmployerService',
        ),
        migrations.AddField(
            model_name='subservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='services.service'),
        ),
        migrations.AddField(
            model_name='offer',
            name='subservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='services.subservice'),
        ),
    ]
