# Generated by Django 4.2.1 on 2024-04-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='service_time',
            field=models.TimeField(),
        ),
    ]
