# Generated by Django 4.2.1 on 2024-04-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='employee',
            new_name='assigned_employee',
        ),
        migrations.AddField(
            model_name='order',
            name='approved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
